### ISSUE TITLE
RFC: Prevent mutating returned fixtures

### ISSUE THREAD

**Issue by levithomason** [TechnologyAdvice/fixd#2]
We have issues with fixtures being passed around and mutated after they are created.  This proposal solves this issue by freezing all returned fixtures.

>Wait, how will we hand craft individual fixtures?

An API is also proposed for extending fixtures before they are frozen and returned.

***

# Proposal

Add some fixtures, as usual:

```js
fixd.addObject('obj', { foo: 'bar' })
fixd.addArray('arr', ['foo', 'bar'])
fixd.addJSON('json', { foo: 'bar' })
```

## Access immutable fixtures

Most use cases simply need to access the fixture or one of its properties.  Offer simple access to fixtures:

```js
fixd.obj      // { foo: 'bar' }
fixd.arr      // ['foo', 'bar']
fixd.json     // { foo: 'bar' }
```

These are immutable (frozen) and throw if extended or modified:
```js
fixd.obj.newProp = 'works?'
// TypeError: Cannot add property newProp, object is not extensible

fixd.obj.foo = 'override?'
// TypeError: Cannot assign to read only property 'foo' of object '#<Object>'
```

## Create a mutated fixture

We sometimes need to use a modified fixture.  The `fixd.create()` method is reserved for creating mutated fixtures. 

Most use cases simply need to extend an object:

```js
fix.create('obj', { baz: 'qux' })
// => { foo: 'bar', baz: 'qux' }
```

Some cases need more than simple extension:
```js
fix.create('obj', obj => {
  delete obj.foo
  obj.fooGone = true
  return obj
})
// => { fooGone: true }
```

The extend/callback pattern applies to all types:
```js
fix.create('arr', ['baz'])
// => ['foo', 'bar', 'baz']

fix.create('arr', arr => ['which', ..._.pull('foo', arr), '?'])
// => ['which', 'bar', '?']
```

```js
fix.create('json', { extended: true })
// => { foo: 'bar', extended: true }

fix.create('json', json => {
  delete json.foo
  json.fooGone = true
  return json
})
// => { fooGone: true }
```

**Comment by dvdzkwsk** [comment]
👍  on immutability, 👎  on an API difference with magical getters vs. the `create` method. I simply don't think the characters saved are worth the extra API surface area. My proposal:

1) `fix.create('foo') // => immutable`
2) `fix.create('foo', foo => { /* modify and return */ }) // => immutable after return`.

Would prefer a consistent API between both, and that way it's easy to switch from unmodified -> modified without changing how fixd is used.

**Comment by levithomason** [comment]
These aren't magical getters in this case, they are literally native sealed objects.  There is no reason to create fresh objects on every call when they are sealed.  The engine will not allow mutating them.

**Comment by levithomason** [comment]
My argument is that instead of internally creating a new immutable copy every time, we simply allow direct access to the immutable singleton.

**Comment by dvdzkwsk** [comment]
They are magical getters. Why should I have to do:

`fix.addObject('foo')`

to add something, and then use a _different type of API_ to access it?

`fix.foo`

Notice how the setter and getter are different? I simply don't think the API change is worth shaving a few characters.

**Comment by levithomason** [comment]
Forgoing recursive freezing and safeguards, this is the naive implementation I'm suggesting:

```js
const fixd = {
  addObject: (name, obj) => fixd[name] = Object.freeze(obj)
}
```

I'm not seeing a good reason to re-create the frozen object every time it is accessed.

**Comment by dvdzkwsk** [comment]
My brain dump:

```js
fix = (() => {
  const objects = {}
  return {
    add: (key, value) => objects[key] = freeze(value),
    create: (key) => objects[key]
  }
})()
```

Sane API. It's not recreating anything... But ultimately you're missing the forest for the trees. I'm not talking about recreating the object. That's an implementation detail that can be avoided, as in my example. I am speaking of API consistency.

**Comment by dvdzkwsk** [comment]
I'll leave at this:

1) 👍  for _deeply_ sealed (frozen?) objects.
2) 👍  for throwing errors if fixtures are mutated. This will help catch unintentional mutations.
3) 👎  for differing API's between fixture usage w/ and w/o modifiers.

Your call on how you think the API should look, but being an RFC I felt it necessary to stress my insecurity about the proposed shorthand.

**Comment by levithomason** [comment]
I see.  I'm referring to syntax and method name I guess more than the implementation.  As in `fixd.create()`ing a fixture vs "accessing" it via property.

In my mind, the `create()` method is reserved for instantiating a new instance of a fixture (creating a fixture) where as most the time I just want to access one, `fixd.obj`.

Personally, regarding `fixd.program` vs `fixd.create('program')`, I think the extra characters (`.create('')`) are making the code harder to read due to the clutter.

In either case, all opinions are fair and thanks for sharing.  We'll go with majority vote to kill the bike shedding and get max satisfaction.

**Comment by ksafranski** [comment]
A little late to the convo, but my thought would be to just give it a very obvious API syntax:

```javascript
// Add as per usual...
fixd.addObject('foo', { foo: 'bar' })

// Create a "standard" fixture object
fixd.create('foo', /* optional modifier... */)

// Create a frozen fixture object
fixd.create.frozen('foo', /* optional modifier... */)
```

**Comment by levithomason** [comment]
What's the use case for a mutable fixture?
