### ISSUE TITLE
Adding type declarations

### ISSUE THREAD

**Issue by ElliottCampbellJHA** [TechnologyAdvice/fixd#5]
I'm going through some of our `.d.ts` files that we are wanting to upload to either the source repos or DefinitelyTyped. Currently, this package lacks any type declarations for TypeScript integration. 

@eheikes specifically mentioned reaching out here for a response about placing the declaration here before moving on to placing it in DefinitelyTyped.

If it's all good to do so, I can have a PR ready within the following business day after the response.

**Comment by roguefalcon** [comment]
I think I'm following you.  If you can make a PR that would be great.
